--- 
title: "Advance Mathematic MCOMD0AMA"
author: "Dr. Alexios Louridas"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This book contains the material that would be covered in the module. It would start from Basic GCSE maths to some more advance topics for Computing."
---

# Introduction {-}

## Module Structure {-}

We are going to have 12 weeks of teaching. What we would like at the end of this module is for you to be able to have enough knowledge to be able to understand mathematics so you can easily understand concepts that you will find in your course that you are going to follow.

Mathematics is not just about learning how to solve problems but 

The indicative schedule we are going to follow can be seen in table 0.1. Although we shall try and follow this schedule it all depends on you. If you believe that you need an extra session to describe and master something then we are here to listen. Please tell us and we shall try to change it accordingly.

```{r echo = FALSE}
c<- matrix(c(0,1,2,3,4,5,6,7,8,9,10,11,"Numbers","Algebra - Basics","Algebra - Quadratics and Simultaneous Equations","Geometry and thinking","Graphs and Coordinate Geometry","Probability and Statistics","Polynomials","Logarithms and Exponential","Introduction to Discrete Mathematics","Systems","Summary and Revision, TCA", "Assignment"),ncol=2)
colnames(c) <- c("Session","Indicative Content")

knitr::kable(c,
  caption = 'Indicative Content Schedule.',align = "cc", booktabs = FALSE
)
```

## Assignment {-}

TCA 40% 
The TCA will consist of a series of tasks, each examining one area of mathematics.  Each task will include a practical element requiring students to interpret a specification, identify an appropriate area of mathematics and apply the relevant formulae to each problem in order calculate a solution.  The aim of the TCA is to ensure students have a good grounding in basic mathematical concepts and will avoid any issues associated with plagiarism.  Some, but not all topics will be assessed through the TCA.

The second assessment will also be a group report and will consist of a single group task.  The tasks will be based on front loaded teaching material and supplemented by students own independent research into the discipline.  The aim of this assessment is to allow students to work more co-operatively within the field of mathematics and appreciate that it is possible to collectively solve complex problems by the use of functional or task decomposition.  A typical group task might involve all or some of the following: an investigation into a novel domain; the derivation of appropriate mathematical formulae or models; the application of these to an identified domain problem; a formal proof; statistical analysis of any results; a forecast of results.
